reads_file: reads.bam
clade_ranks: 
 - species
 - order
 - genus
output_style: long
threads:
    hmmer:    2
    lastal:   10
    prodigal: 20
aa_conversion: prodigal
dbs:
    RefSeq: 
        path: /seqdbs/RefSeq/lastdb
        format: lastp
        type: tax
    KEGG: 
        path: /seqdbs/KEGG/lastdb
        format: lastp
        assign_type: kegg
    COG:
        path: /seqdbs/COG/frag-8/COG.{N}.hmm
        frags: 8
